name: "CI"
on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v33
        with:
          nix_version: "2.31.0"
      - name: Install omnix
        run: nix profile install nixpkgs#omnix
      - name: Build all flake outputs
        run: om ci
      - name: Run it in Nix
        run: nix run
      - name: Run it in Cabal
        run: nix develop -c cabal run hint-demo
